# Generated by Django 5.2.8 on 2025-11-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('supervisor', models.CharField(max_length=120)),
                ('zona', models.CharField(max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('completa', 'Completa'), ('pendiente', 'Pendiente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('cumplido', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=30)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='visitas.visita')),
            ],
        ),
    ]
